lint:
	black test_game_of_life_sandeep_singh.py
	isort test_game_of_life_sandeep_singh.py
	flake8 test_game_of_life_sandeep_singh.py

test:
	pytest .

lint-check:
	black . --check
	isort . --check
	flake8 .
