lint-check:
	black test_game_of_life.py --check
	isort test_game_of_life.py --check
	flake8 test_game_of_life.py


lint:
	black test_game_of_life.py
	isort test_game_of_life.py
	flake8 test_game_of_life.py


test:
	pytest test_game_of_life.py