lint:
 	black model_definition.py
 	isort model_definition.py
 	flake8 model_definition.py
 	black model_training.py
 	isort model_training.py
 	flake8 model_training.py
 	black endpoint.py
 	isort endpoint.py
 	flake8 endpoint.py

lint-check:
 	black . --check
 	sort . --check
 	flake8 .