lint-check:
	black test_game_of_life_rachel2.py --check
	isort test_game_of_life_rachel2.py --check
	flake8 test_game_of_life_rachel2.py


lint:
	black test_game_of_life_rachel2.py
	isort test_game_of_life_rachel2.py
	flake8 test_game_of_life_rachel2.py

test:
	pytest test_game_of_life_rachel2.py
