lint-check:
	black test_game_of_life_rachel.py --check
	isort test_game_of_life_rachel.py --check
	flake8 test_game_of_life_rachel.py


lint:
	black test_game_of_life_rachel.py
	isort test_game_of_life_rachel.py
	flake8 test_game_of_life_rachel.py

test:
	pytest test_game_of_life_rachel.py
