lint-check:
	black test_game_of_life_rachel_cao.py --check
	isort test_game_of_life_rachel_cao.py --check
	flake8 test_game_of_life_rachel_cao.py


lint:
	black test_game_of_life_rachel_cao.py
	isort test_game_of_life_rachel_cao.py
	flake8 test_game_of_life_rachel_cao.py

test:
	pytest test_game_of_life_rachel_cao.py
