lint:
	black YI_SUN/test_game_of_life.py
	isort YI_SUN/test_game_of_life.py
	flake8 YI_SUN/test_game_of_life.py

test:
	pytest YI_SUN/test_game_of_life.py

lint-check:
	black YI_SUN/test_game_of_life.py --check
	isort YI_SUN/test_game_of_life.py --check
	flake8 YI_SUN/test_game_of_life.py
