lint:
	black Hakan_Serpen/test_game_of_life.py
	isort Hakan_Serpen/test_game_of_life.py
	flake8 Hakan_Serpen/test_game_of_life.py

test:
	pytest Hakan_Serpen/test_game_of_life.py

lint-check:
	black Hakan_Serpen --check
	isort Hakan_Serpen/test_game_of_life.py --check
	flake8 Hakan_Serpen