lint:
	black Ziling_Zhang/test_game_of_life_ziling_zhang.py
	isort Ziling_Zhang/test_game_of_life_ziling_zhang.py
	flake8 Ziling_Zhang/test_game_of_life_ziling_zhang.py

test:
	pytest .

lint-check:
	black . --check
	isort . --check
	flake8 .